apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring-global
  labels:
    app: prometheus-global
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-global
  template:
    metadata:
      labels:
        app: prometheus-global
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.enable-remote-write-receiver"
            - "--web.enable-lifecycle"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: prometheus-global-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-global-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-global-conf
        - name: prometheus-storage-volume
          emptyDir: {}
