apiVersion: v1
kind: Service
metadata:
  name: prometheus-global-service
  namespace: monitoring-global
spec:
  type: NodePort
  selector:
    app: prometheus-global
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
