apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-global
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 7.3.7
    helm:
      parameters:
        - name: service.type
          value: NodePort
    chart: grafana
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring-global
  syncPolicy:
    automated: {}
