apiVersion: batch/v1
kind: Job
metadata:
  name: upgrade-edge
  namespace: management
spec:
  backoffLimit: 0 
  template:
    spec:
      containers:
      - name: upgrade-edge-container
        image: ghcr.io/eficode-academy/edgek8s-upgrade:latest
        env:
          # - name: UPGRADE_TALOS
            # value: "true"
          - name: TALOS_VERSION
            value: "v1.4.6"
          # - name: UPGRADE_KUBERNETES
            # value: "true"
          - name: KUBERNETES_VERSION
            value: "v1.27.4"
        volumeMounts:
        - mountPath: /var/run/secrets/talos.dev
          name: talos-secrets
        - mountPath: /opt/kubeconfig
          name: kubeconfig-volume
        - mountPath: /opt/talosconfig
          name: talosconfig-volume
      volumes:
      - name: talos-secrets
        secret:
          secretName: management-deployment-talos-secrets
      - name: kubeconfig-volume
        secret:
          defaultMode: 420
          secretName: kubeconfig-secret
      - name: talosconfig-volume
        secret:
          defaultMode: 420
          secretName: talosconfig-secret
      restartPolicy: Never
