apiVersion: batch/v1
kind: Job
metadata:
  name: upgrade-edge
spec:
  backoffLimit: 0 
  template:
    spec:
      containers:
      - name: upgrade-edge-contaienr
        image: ghcr.io/eficode-academy/edgek8s-upgrade:latest
        env:
          - name: UPGRADE_TALOS
            value: "true"
          - name: TALOS_VERSION
            value: "v1.4.8"
          # - name: UPGRADE_KUBERNETES
          #   value: "true"
      restartPolicy: Never
